title: Shekela Best # your name (or website title) here
logo: "/images/pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Teacher  ➡️ Data analyst
  <br><br>
  Taking complexity and transform it into beautiful simplicity
  <br><br>
  <a href="https://www.linkedin.com/in/shekela-mitchell-best/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
